# this is for now just a rough draft

services:
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
  api:
    build:
      context: ./packages/api
    command: pnpm run dev -- --noClear
    working_dir: /usr/src/api
    volumes: 
      - ./packages/api:/usr/src/api
  # todo: gateway
  # todo: leaf
  # todo: wind
  ## Internal services
  singyeong:
    image: queer/singyeong:2021-02-05_00.52.16-7eb38d
    ports:
      - 4567:4567
    environment:
      PORT: 4567
  ## Databases
  scylla:
    image: scylladb/scylla
    ports:
      - 9042:9042
    volumes:
      - db-data:/var/lib/scylla/data
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
  sonic:
    image: valeriansaliou/sonic:v1.3.0
    ports:
      - 1491:1491
    volumes:
      - ./dev/sonic.cfg:/etc/sonic.cfg
      - search-data:/var/lib/sonic

volumes:
  db-data:
    driver: local
  search-data:
    driver: local
