name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.15.0
          run_install: true
      - name: lint
        run: make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.15.0
          run_install: true
      - name: start services
        run: docker-compose -p squirrel_test -f docker-compose.test.yml up -d
      - name: test
        run: make test
      - name: stop services
        if: ${{ always() }}
        run: docker-compose down
